name: peri_team_hotel_app
description: A Flutter app to log hotels to avoid based on user feedback and map pins.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  firebase_core: ^3.14.0
  firebase_database: ^11.3.7
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.5+4
  geocoding: ^4.0.0
  intl: ^0.20.2
  share_plus: ^11.0.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
